<a href="https://colab.research.google.com/github/CommunityRADvocate/ida-colabs/blob/main/week_10_numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

* Stands for "Numerical Python"
* Deals with numerical data and mathematical equations in a more efficient way than regular Python
* Offers advanced mathematical functions and simplifies many numerical concepts

## Introducing Arrays

* Common data structure in many programming languages
* NumPy arrays are more restrictive than regular Python lists
    * Elements must be of the same data type
    * They are immutable

Why would we want a more restrictive structure?

In [ ]:
import numpy as np

# create a list
my_list = [1, 2, 3, 4, 5]

# convert list to a numpy array
my_array = np.array(my_list)

# print the array
print(my_array)

[1 2 3 4 5]


## Multidimensional Arrays

We'll create a 2D array, aka matrix

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can access specific elements in the array by specifying their row and column index

In [ ]:
# what will I get when I run this?
elements = matrix[1][2]
elements = matrix[1, 2]
elements

6

We can get the shape (how many rows and columns) and size (how many total elements) that are in our matrix

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix.size

9

## Indexing

Besides directly specifying row and column index, we can use more advanced techniques

In [ ]:
# create a list of numbers from 0 to 9
my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.lookfor("arange")

In [ ]:
first_element = my_list[0]
second_element = my_list[1]
first_element, second_element

(0, 1)

In [ ]:
subset = my_list[2:4]
subset

array([2, 3])

## Boolean Array Indexing

In [ ]:
data = np.array([75, 40, 90, 55, 68, 30, 82, 95, 42, 78])

In [ ]:
# view all elements that are less than 60
failing = data[data < 60]
failing

array([40, 55, 30, 42])

## Slicing

* Returns views, not copies
    * This means you need to be mindful of manipulating values on slices if you don't intend to change the original dataset

In [ ]:
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sliced_list = my_list[2:6]
sliced_list

array([2, 3, 4, 5])

In [ ]:
sliced_list[0] = 11
my_list, sliced_list

(array([ 0,  1, 11,  3,  4,  5,  6,  7,  8,  9]), array([11,  3,  4,  5]))